apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-delta-refined
  namespace: atlas
  labels:
    app.kubernetes.io/component: delta-lake
    app.kubernetes.io/name: atlas-lakehouse
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: atlas-shared
  resources:
    requests:
      storage: 20Gi
  selector:
    matchLabels:
      app.kubernetes.io/name: atlas-lakehouse
