@echo off
echo Stopping any running containers (preserving data)...
docker-compose --profile full-cluster down
echo Starting Atlas Stack (Broker + API + Airflow)...
docker-compose up -d broker1 kafka-init atlas-ingestion airflow-db airflow-webserver airflow-scheduler atlas-processor atlas-lakehouse atlas-analytics
echo Done! Run 'docker ps' to check status.