# Nginx for all-in-one container
upstream power_api {
    server 127.0.0.1:8000;
    keepalive 64;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://power_api;
        proxy_http_version 1.1
