apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atlas-spark-checkpoint
  namespace: atlas
  labels:
    app.kubernetes.io/component: processing
    app.kubernetes.io/name: atlas-processor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 5Gi
