apiVersion: v1
kind: Secret
metadata:
  name: atlas-credentials
  namespace: atlas
  labels:
    app.kubernetes.io/component: frontend
type: Opaque
stringData:
  POSTGRES_USER: atlas
  POSTGRES_PASSWORD: atlas_secure_pwd
  POSTGRES_DB: atlas_metadata
  CLICKHOUSE_USER: atlas
  CLICKHOUSE_PASSWORD: atlas_secure_pwd
