apiVersion: v1
kind: Service
metadata:
  name: atlas-streamlit
  namespace: atlas
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/name: atlas-streamlit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: atlas-streamlit
  ports:
    - name: http
      port: 8501
      targetPort: http
      protocol: TCP
