-- ============================================================================
-- TVMJNS — PostgreSQL Database Schema
-- 
-- Creates tables for storing streaming telemetry data and alerts.
-- Run this once to initialize the database.
-- ============================================================================

-- ── Telemetry Readings Table ────────────────────────────────────────────────
-- Stores raw sensor readings ingested from Kafka
CREATE TABLE IF NOT EXISTS telemetry_readings (
    id              BIGSERIAL PRIMARY KEY,
    sensor_id       VARCHAR(50) NOT NULL,
    recorded_at     TIMESTAMPTZ NOT NULL,
    temperature     DECIMAL(5,2),
    humidity        DECIMAL(5,2),
    pressure        DECIMAL(7,2),
    battery_level   DECIMAL(5,2),
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    -- Index for time-series queries
    CONSTRAINT chk_temperature CHECK (temperature BETWEEN -50 AND 100),
    CONSTRAINT chk_humidity CHECK (humidity BETWEEN 0 AND 100),
    CONSTRAINT chk_battery CHECK (battery_level BETWEEN 0 AND 100)
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_telemetry_sensor_id ON telemetry_readings(sensor_id);
CREATE INDEX IF NOT EXISTS idx_telemetry_recorded_at ON telemetry_readings(recorded_at DESC);
CREATE INDEX IF NOT EXISTS idx_telemetry_sensor_time ON telemetry_readings(sensor_id, recorded_at DESC);


-- ── Sensors Registry Table ──────────────────────────────────────────────────
-- Metadata about registered sensors
CREATE TABLE IF NOT EXISTS sensors (
    sensor_id       VARCHAR(50) PRIMARY KEY,
    name            VARCHAR(100),
    location        VARCHAR(200),
    installed_at    TIMESTAMPTZ,
    last_seen_at    TIMESTAMPTZ,
    status          VARCHAR(20) DEFAULT 'active',
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


-- ── Alerts Table ────────────────────────────────────────────────────────────
-- Stores alerts generated by the streaming pipeline
CREATE TABLE IF NOT EXISTS alerts (
    id              BIGSERIAL PRIMARY KEY,
    sensor_id       VARCHAR(50) NOT NULL,
    alert_type      VARCHAR(50) NOT NULL,
    severity        VARCHAR(20) NOT NULL DEFAULT 'warning',
    message         TEXT,
    triggered_at    TIMESTAMPTZ NOT NULL,
    acknowledged    BOOLEAN DEFAULT FALSE,
    acknowledged_at TIMESTAMPTZ,
    acknowledged_by VARCHAR(100),
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT chk_severity CHECK (severity IN ('info', 'warning', 'critical'))
);

CREATE INDEX IF NOT EXISTS idx_alerts_sensor_id ON alerts(sensor_id);
CREATE INDEX IF NOT EXISTS idx_alerts_triggered_at ON alerts(triggered_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_unacknowledged ON alerts(acknowledged) WHERE acknowledged = FALSE;


-- ── Aggregated Statistics Table ─────────────────────────────────────────────
-- Stores hourly/daily aggregations computed by Spark
CREATE TABLE IF NOT EXISTS telemetry_stats (
    id              BIGSERIAL PRIMARY KEY,
    sensor_id       VARCHAR(50) NOT NULL,
    period_start    TIMESTAMPTZ NOT NULL,
    period_end      TIMESTAMPTZ NOT NULL,
    period_type     VARCHAR(20) NOT NULL,  -- 'hourly', 'daily'
    reading_count   INTEGER NOT NULL,
    temp_min        DECIMAL(5,2),
    temp_max        DECIMAL(5,2),
    temp_avg        DECIMAL(5,2),
    humidity_min    DECIMAL(5,2),
    humidity_max    DECIMAL(5,2),
    humidity_avg    DECIMAL(5,2),
    created_at      TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uq_stats_sensor_period UNIQUE (sensor_id, period_start, period_type)
);

CREATE INDEX IF NOT EXISTS idx_stats_sensor_period ON telemetry_stats(sensor_id, period_start DESC);


-- ── Insert Sample Sensors ───────────────────────────────────────────────────
INSERT INTO sensors (sensor_id, name, location, installed_at, status)
VALUES 
    ('sensor_001', 'Temperature Sensor A', 'Building 1 - Floor 1', '2026-01-01 00:00:00+00', 'active'),
    ('sensor_002', 'Temperature Sensor B', 'Building 1 - Floor 2', '2026-01-01 00:00:00+00', 'active'),
    ('sensor_003', 'Temperature Sensor C', 'Building 2 - Floor 1', '2026-01-15 00:00:00+00', 'active'),
    ('sensor_004', 'Temperature Sensor D', 'Building 2 - Floor 2', '2026-01-15 00:00:00+00', 'active'),
    ('sensor_005', 'Temperature Sensor E', 'Building 3 - Roof', '2026-02-01 00:00:00+00', 'active')
ON CONFLICT (sensor_id) DO NOTHING;


-- ── Helpful Views ───────────────────────────────────────────────────────────

-- Latest reading per sensor
CREATE OR REPLACE VIEW v_latest_readings AS
SELECT DISTINCT ON (sensor_id)
    sensor_id,
    recorded_at,
    temperature,
    humidity,
    pressure,
    battery_level
FROM telemetry_readings
ORDER BY sensor_id, recorded_at DESC;


-- Unacknowledged alerts
CREATE OR REPLACE VIEW v_active_alerts AS
SELECT 
    a.id,
    a.sensor_id,
    s.name as sensor_name,
    s.location,
    a.alert_type,
    a.severity,
    a.message,
    a.triggered_at
FROM alerts a
LEFT JOIN sensors s ON a.sensor_id = s.sensor_id
WHERE a.acknowledged = FALSE
ORDER BY 
    CASE a.severity 
        WHEN 'critical' THEN 1 
        WHEN 'warning' THEN 2 
        ELSE 3 
    END,
    a.triggered_at DESC;


-- ============================================================================
-- Done! Tables created successfully.
-- ============================================================================
