apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-processor
  namespace: atlas
spec:
  template:
    spec:
      containers:
        - name: spark-processor
          resources:
            requests:
              cpu: "300m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "3Gi"
